trigger:
- main

variables:
  azureSubscription: 'AzureServiceConnection'
  functionAppName: 'fa-twinkle-nodejs-cicd'
  nodeVersion: '18.x'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build the Function App'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: ''

    - script: |
        npm install
      displayName: 'Install dependencies'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: ''
        includeRootFolder: false
        archiveType: zip
        archiveFile: '/.zip'
        replaceExistingArchive: true

    - publish: '/.zip'
      artifact: 'drop'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: ''

    - script: |
        npm install
        npm test
      displayName: 'Run unit tests'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Test
  jobs:
  - deployment: Deploy
    environment: 'production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: ''
              appType: 'functionApp'
              appName: ''
              package: '/drop/.zip'
              deploymentMethod: 'auto'
              runtimeStack: 'NODE|18'
